ALTER TABLE "Row" 
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

UPDATE "Row" 
SET "updatedAt" = CURRENT_TIMESTAMP 
WHERE "updatedAt" IS NULL;

ALTER TABLE "Row" 
ALTER COLUMN "updatedAt" SET NOT NULL;
